travis:
  secure:
    BINSTAR_TOKEN: SDCx+1ze+kINN7+ozhWXp61mCdKcrMrH1w1TakkJDqdOUtjBLvi/fU/C64rQs4iUYjqtY+zQlK5OzL+OmRZC47FFPC3DW3gtpOjNpWRhqSggr72hECiTXJB7CdE4iDqe6vSMv1eTQaWxEgcd80y718hPVzreSgxnnlj+AAOoL60FWHUPhBqt0oMQhQszuEisv/1clJbkALJPRkY1O5JmyOvovb1EVzRwKoyDB7aRkiD/sBdKC6dYiYYU5hhfx8g64BjvqDXNDT9R61O5E6vpanwNUwGZd6LGMKqrnP5Wz1YNfhBQMaxeUx5n4Y7Igk7hw9nhSIcalMSTpx83p33IMQgXi9HDTLDQ7jYebFdU8eA7gy9WbR6s0p9ea0dtFytES31UmLHtFA3MxfWEghH0YgUUI2HGQ/2hEhfXSTv6y9ryYM8fs6Fd5VkZ3MO8qAdyRM2amZGM1tN99MK3nFm9Y/hOJ7CK/Gns+wNkxsZerW8AP+qCP4QgB8K2zZEs3fUQ3d1uttLwUpF8x9J1Afd+gf92go6bzM6WyYPwaB/81Ck7Plx8WtjKgtE7cMRZxCLMfV/eYMahroMSE72uMLqZ9VjIRXNYTfwI0K2SHzMhZltrpP1HxqQp831IaBPUWKqxHPzL8ZZLgGeVDlLIzknAt0dsmdvmcS42preD2KlxVKE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
